const ALARMACTIONS = {
    UPDATE_ALARM: 'UPDATE_ALARM',
}
/*
const PAGESACTIONS = {
    UPDATE_PATH: 'UPDATE_PATH',
}

const SELECTACTIONS = {
    SELECT_DATA: 'SELECT_DATA',
    SELECT_AREA: 'SELECT_AREA',
    SELECT_UNIT: 'SELECT_UNIT',
}

const LOGIN = {
    ACTIVATE: 'ACTIVATE',
    DEACTIVATE: 'DEACTIVATE',
}
*/
export { ALARMACTIONS }